name: lyricapture
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  get_it: ^8.0.3
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  # image_gallery_saver: ^2.0.3
  injectable: ^2.5.0
  palette_generator: 0.3.3+7
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  screenshot: ^3.0.0
  share_plus: ^7.2.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
